---
- name: Playbook for VPC
  hosts: localhost
  gather_facts: no
  vars_files:
    - configurations/regions
  tasks:
    - name: VPC for class
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tags:
          Class: Ansible
          Task: VPC