---
- name: Playbook for Provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        assign_public_ip: yes
        region: "{{region}}"