---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create repo
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d/

    - name: Install agent
      package:
        name: serverbackup-enterprise-agent
        state: present
      
    - name: Get Key
      shell: "r1soft-setup --get-key http://34.245.178.242:8080"

    - name: Start agent
      systemd:
        name:  sbm-agent
        state: restarted

    - name: Stop firewalld
      systemd: 
        name: firewalld
        state: stopped
        enabled: false