---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install multiple packages
      package:
        name: "{{item}}"
        state: present
      with_items:
        - telnet
        - lftp
        - firewalld 
        - curl 
        - gzip 
        - httpd 
        - openssh-server