---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Start apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
    - name: Install telnet
      yum: 
        name: telnet
        state: latest
    - name: Add user bob
      user: 
        name: bob
        state: present
        comment: "Bob Smith"
        group: wheel
        uid: 2001
        create_home: yes
        expires: 1422403387
        generate_ssh_key: yes
    - name: Install lftp
      package:
        name: lftp
        state: present