---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Add multiple users
      user:
        name: "{{item}}"
        state: present
      with_items:
        - bob 
        - sam 
        - ben 
        - tim 